// Regenerates supabase/seed.sql from src/shop/products.js.
//   npm run seed:sql
// Re-running the seed updates names/categories but never overwrites prices
// that staff have already set in Supabase.
import { writeFileSync } from 'node:fs';
import { PRODUCTS, SIGNATURES } from '../src/shop/products.js';

const q = (v) => (v === null || v === undefined ? 'null' : `'${String(v).replace(/'/g, "''")}'`);
const rows = [...PRODUCTS, ...SIGNATURES].map(
  (p) => `  (${q(p.id)}, ${q(p.name)}, ${q(p.sheetName ?? null)}, ${q(p.category)}, ${p.number}, ${p.inspired}, ${p.price ?? 'null'}, ${q(p.description ?? null)})`,
);

const sql = `-- Generated by scripts/seed-sql.mjs from src/shop/products.js — do not edit by hand.
-- Safe to re-run: prices and descriptions already set in Supabase are kept.
insert into public.products (id, name, sheet_name, category, number, inspired, price, description)
values
${rows.join(',\n')}
on conflict (id) do update set
  name       = excluded.name,
  sheet_name = excluded.sheet_name,
  category   = excluded.category,
  number     = excluded.number,
  inspired   = excluded.inspired,
  price       = coalesce(public.products.price, excluded.price),
  description = coalesce(public.products.description, excluded.description);
`;

writeFileSync(new URL('../supabase/seed.sql', import.meta.url), sql);
console.log(`supabase/seed.sql written: ${rows.length} products`);
