// Regenerates supabase/seed.sql from the catalogue (src/shop/products.js,
// fed by the spreadsheet via `npm run import:products`).
//   npm run seed:sql
// Re-running is safe: a price or stock figure from the spreadsheet updates
// Supabase, while an empty spreadsheet cell never wipes a value that staff
// set in the Supabase dashboard.
import { writeFileSync } from 'node:fs';
import { PRODUCTS, SIGNATURES } from '../src/shop/products.js';

const q = (v) => (v === null || v === undefined ? 'null' : `'${String(v).replace(/'/g, "''")}'`);
const n = (v) => (v === null || v === undefined ? 'null' : Number(v));
const rows = [...PRODUCTS, ...SIGNATURES].map(
  (p) => `  (${q(p.id)}, ${q(p.name)}, ${q(p.sheetName ?? null)}, ${q(p.category)}, ${p.number}, ${p.inspired}, ${n(p.price)}, ${n(p.stock)}, ${q(p.description ?? null)})`,
);

const sql = `-- Generated by scripts/seed-sql.mjs from the product spreadsheet — do not edit by hand.
-- Safe to re-run: spreadsheet prices/stock update Supabase; empty cells keep Supabase values.
insert into public.products (id, name, sheet_name, category, number, inspired, price, stock, description)
values
${rows.join(',\n')}
on conflict (id) do update set
  name        = excluded.name,
  sheet_name  = excluded.sheet_name,
  category    = excluded.category,
  number      = excluded.number,
  inspired    = excluded.inspired,
  price       = coalesce(excluded.price, public.products.price),
  stock       = coalesce(excluded.stock, public.products.stock),
  description = coalesce(public.products.description, excluded.description);
`;

writeFileSync(new URL('../supabase/seed.sql', import.meta.url), sql);
console.log(`supabase/seed.sql written: ${rows.length} products`);
